### ISSUE TITLE
Raw Format for Responses

### ISSUE THREAD

**Issue by GollyTicker** [qaware/protocurl#10]
If no .proto files for the response are available, then it's still possible to receive and decode messages. The decoding can happen in a way which only shows the field numbers and the field contents - without the field names; essentially `protoc --decode_raw`. This might be useful for users of protoCURL.

- [x] write tests
- [x] decide how to implement. The [Java Protobuf SDK seems to have this functionality](https://github.com/protocolbuffers/protobuf/blob/520c601c99012101c816b6ccc89e8d6fc28fdbb8/java/core/src/test/java/com/google/protobuf/TextFormatTest.java#L246)
- [x] documentation (see #52)

**Comment by 89z** [comment]
https://github.com/qaware/protocurl/issues/51

**Comment by 89z** [comment]
I am interested in this feature. However I will say, Protocol Buffers is an inherently flawed protocol, in that it is not self describing. This is evidenced by the fact that "type 2" wire type [A], can be any of these values:

1. string
2. byte slice
3. embedded message

Its pretty straight forward to check for string or byte slice [B]. Also, not all input is a valid message. That gives you this result:

valid string | valid message | result
-------------|---------------|-----------
no           | no            | byte slice
no           | yes           | message or byte slice
yes          | no            | string
yes          | yes           | message or string

Ideally the protocol would have an extra wire type, for example "type 6", to designate embedded messages. But without that, its not possible in every case to know the structure of the input, unless you have a schema. One workaround for this, is when the input is ambiguous, you could add both types under the same key:

~~~go
map[int]any{
   1: "one is a string",
   -1: map[int]any{2: "negative one is embedded message"},
}
~~~

A. https://developers.google.com/protocol-buffers/docs/encoding
B. https://github.com/89z/format/blob/v1.34.0/format.go#L17-L35

**Comment by GollyTicker** [comment]
Thanks for your feedback and the background information.

I was not aware of this ambiguity in parsing payloads without the schema. Though I am not entirely surprised, as this is not how protobuf should be used anyways (in my understanding).

I am curious in how `protoc --decode-raw` deals with that for concrete examples.

**Usage**
I am thinking of making the argument `-o <response-type>` optional. If not provided, protocurl would show the message with field numbers and inferred field types instead of field names and correct types. Otherwise, I could make this use case explicit with `-o ?` or `--decode-raw`. The `?` would indicate, that the response message type is unknown - and that it should hence decode the raw input.

**Implementation**
My first attempt would be the use of `EmitUnknown` in the [prototext.MarshalOptions](https://pkg.go.dev/google.golang.org/protobuf/encoding/prototext#MarshalOptions) and use the message type [Empty](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/empty.proto#L51). My hope is, that this way the response will be similar to `protoc --decode_raw`.
However, [protojson.MarshalOptions](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#MarshalOptions) seems to not support the output of unknown fields by their field numbers. This could be an issue.

What are your thoughts?

**Comment by 89z** [comment]
> I was not aware of this ambiguity in parsing payloads without the schema. Though I am not entirely surprised, as this is not how protobuf should be used anyways (in my understanding).

Its quite unfortunate really. JSON is self describing, nothing is stopping ProtoBuf from being self describing as well. Granted, you lose the field names, but even just having the field numbers and values, with a defined structure as read from the input, would be quite useful. Quoting from the spec [1]:

> in other words, the last three bits of the number store the wire type

So that gives you this currently:

~~~
000 Varint
001 64-bit
010 Length-delimited
011 Start group
100 End group
101 32-bit
110
111
~~~

So you have at least two extra types that could be added. Even a single extra type for embedded messages would essentially make ProtoBuf self describing.

1. https://developers.google.com/protocol-buffers/docs/encoding

> I am curious in how `protoc --decode-raw` deals with that for concrete examples.

Sorry I haven't used that in a while, so I'm not sure what it does.

> **Usage** I am thinking of making the argument `-o <response-type>` optional. If not provided, protocurl would show the message with field numbers and inferred field types instead of field names and correct types. Otherwise, I could make this use case explicit with `-o ?` or `--decode-raw`. The `?` would indicate, that the response message type is unknown - and that it should hence decode the raw input.

I don't really have feedback on the actual implementation, only that one should exist. If it helps, I found these packages to be useful:

- https://godocs.io/google.golang.org/protobuf/encoding/protowire
- https://godocs.io/google.golang.org/protobuf/testing/protopack

**Comment by GollyTicker** [comment]
Thanks for the pointers to proto wire and protopack. Though I will see to what extent that will be necessary.

Regarding the lack of self-describing nature of Protobuf. I cannot change it and this would be a major change in the format for protobuf anyways. I don't think, that the lack of self-description is a problem - as you should also have the corresponding schema files.
It's similar to type erasure in programming language compilers. If there is not reflection in a language and the compile time static typing prevents errors, then storing type information at runtime is unnecessary and bloating.

And in special cases protobuf still has the Any type which enables one to provide the full schema as part of the payload.

**Comment by 89z** [comment]
I am unsubscribing to this thread. I don't wish to have a debate about the ProtoBuf spec, as its a point of frustration for me. If you need me for anything further, feel free to "at" me.

**Comment by GollyTicker** [comment]
@89z For now, I am only implementing the case with the Protobuf Text Format output (and not Protobuf JSON Format).

Hence, this Protobuf message ([schema](https://github.com/qaware/protocurl/blob/main/test/proto/happyday.proto#L23))
```
isHappyDay: true
reason: "Thursday is a Happy Day! ⭐"
formattedDate: "Thu, 13 Jan 2022 03:35:39 GMT"
```
would show as
```
1: 1
2: "Thursday is a Happy Day! ⭐"
3: "Thu, 01 Jan 1970 00:00:00 GMT"
4: ""
```
when invoked with `--decode-raw`.

**Comment by 89z** [comment]
I don't think your wire format is correct. Based on this message:

~~~proto
message HappyDayResponse {
   bool isHappyDay = 1;
   string reason = 2;
   string formattedDate = 3;
   string err = 4;
}
~~~

You'd have a Go struct similar to this:

~~~go
type HappyDayResponse struct {
   IsHappyDay *bool `protobuf:"varint,1"`
   Reason *string `protobuf:"bytes,2"`
   FormattedDate *string `protobuf:"bytes,3"`
   Err *string `protobuf:"bytes,4"`
}
~~~

The Go plugin for `protoc` usually produces pointer types for every field, in order to distinguish between an omitted value, and a zero value. So assuming the error was omitted, the wire format would in fact look like this:

~~~
1: 1
2: "Thursday is a Happy Day! ⭐"
3: "Thu, 01 Jan 1970 00:00:00 GMT"
4: ""
~~~

This is done in order to save bytes. You would only send empty string across the wire, if that was in fact the value of Err. In most cases I would consider a wire format like this an error, regardless if it came from server or client, as you can represent "no error" by just simply omitting the field in the wire data.

**Comment by GollyTicker** [comment]
Looking at the message, you are right. I did a mistake when preparing an example.

The response itself is however correct in the sense, that this is indeed what the server responds. In the [server test code](https://github.com/qaware/protocurl/blob/main/test/servers/server.ts#L91) I actually always provide the `err` field. Since it's set to `""` by default, it does only render in the raw format and not in usual usage.

You are right, in that I would not need to provide this variable.

I am merging this feature and make a new release out of it.

Meanwhile you can take a look at the new usage.
